### PR TITLE
Style changes for PowerShell scripts.

### PR DESCRIPTION
**Pull request by pjh**
Tested: smoke-test passes, still able to SSH to Windows nodes.

CC @yujuhong @mtaufen. Let me know if you have any objections to submitting this PR today. It will likely cause merge conflicts if you have pending changes, sorry for the trouble!

### CODE REVIEW

**Comment by yujuhong** [comment]
LGTM

**Comment by yujuhong** [comment]
Oh I think @mtaufen just merged a PR. Rebase? :-)

**Comment by pjh** [comment]
Merged with latest PRs in windows-up branch and re-tested, everything seems ok.

**Comment by pjh** [comment]
Whoops, meant to squash-and-merge. Will try harder to remember next time.

**Pull request merged**
