### PR TITLE
Default to Windows Server version 1809 for Windows nodes.

### PR DESCRIPTION
**Pull request by pjh**
Removes all references to 1803, including moving "win1803" directory to
just "windows". A single Windows directory suffices for now, if
necessary in the future we can shard it into directories for each
Windows version.

Also switches smoke-test.sh to use containers from
https://hub.docker.com/r/claudiubelu/nettest which have been updated for
1809. This is a temporary change and can be reverted once the official
e2eteam containers have been updated (and possible migrated to a more
official location).

### CODE REVIEW

**Comment by pjh** [comment]
@yujuhong this will update https://testgrid.k8s.io/google-windows#windows-prototype to use 1809. Are we ready to merge this?

cc @mtaufen @jingxu97

**Comment by pjh** [comment]
If everything looks ok after testing this in our private fork, I'll send a PR (https://github.com/pjh/kubernetes/commit/a8edec9b477ad5b81aac1e88013fe0968432a43e already prepared) upstream.

**Comment by yujuhong** [comment]
> @yujuhong this will update https://testgrid.k8s.io/google-windows#windows-prototype to use 1809. Are we ready to merge this?

I think we can merge this to test the windows-up fork. I'm hoping the upstream test job will be running by EOD, so that we can get some good signal before switching there.

**Comment by pjh** [comment]
I've verified that smoke-test.sh passes with a `./hack/e2e.go  -- --up` cluster and a `kube-up.sh` cluster. Will merge this now.

**Pull request merged**
